### ISSUE TITLE
Provide gradle init type completion for bash

### ISSUE THREAD

**Issue by maciekkreft** [gradle/gradle-completion#60] opened 2018-03-28 11:47 UTC
If I write `gradle init --` and press tab it does not expand to expected `gradle init --type`. If I write it down `gradle init --type=` and press tab it does not provide hints like: java-library, groovy-library.

```
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.13.3 x86_64
```

**Comment by eriwen** [comment] 2018-04-03 00:09
Is this in bash or zsh?

**Comment by maciekkreft** [comment] 2018-04-03 11:05
@eriwen it is bash.

> GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
> Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by eriwen** [comment] 2019-02-19 23:03
Let's consider this a duplicate of #33 and follow progress there.

**Closed by eriwen** 2019-02-19 23:03 UTC
Labels: a:feature, for:bash, from:contributor
